// Auto-generated by scripts/generate-issf-rules-data.mjs — 2026-06-11
export interface IssfRuleDocument {
  id: string;
  title: string;
  description?: string;
  category: string;
  section: string;
  webUrl?: string;
  pdfUrl?: string;
  localPath?: string;
}

export const issfRuleCategories = [
  {
    "id": "all",
    "name": "All Documents"
  },
  {
    "id": "rulebook",
    "name": "Rule Book 2026"
  },
  {
    "id": "rifle",
    "name": "Rifle"
  },
  {
    "id": "technical",
    "name": "Technical Rules"
  },
  {
    "id": "integrity",
    "name": "Integrity & Ethics"
  },
  {
    "id": "safeguarding",
    "name": "Safeguarding"
  },
  {
    "id": "disciplinary",
    "name": "Disciplinary"
  },
  {
    "id": "eligibility",
    "name": "Eligibility"
  },
  {
    "id": "doping",
    "name": "Anti-Doping"
  },
  {
    "id": "committees",
    "name": "Committees"
  },
  {
    "id": "ain",
    "name": "AIN Regulations"
  },
  {
    "id": "forms",
    "name": "Forms"
  },
  {
    "id": "guides",
    "name": "Guides & Interpretation"
  }
] as const;

export const issfSourceUrl = 'https://www.issf-sports.org/rules';

export const issfRuleDocuments: IssfRuleDocument[] = [
  {
    "id": "issf-rule-book-2026-edition-2025-first-print-12-2025-effective-1-january-2026",
    "title": "ISSF Rule Book 2026 Edition 2025 First Print 12 2025 Effective 1 January 2026.pdf",
    "category": "rulebook",
    "section": "ISSF Rule Book 2026",
    "webUrl": "https://www.issf-sports.org/rules",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=455&file=ISSF-Rule-Book-2026-Edition-2025-First-Print-12-2025-Effective-1-January-2026.pdf",
    "localPath": "/documents/issf/issf-rule-book-2026-edition-2025-first-print-12-2025-effective-1-january-2026.pdf"
  },
  {
    "id": "update-article-3-13-3-13-annex-ac-athletes-committee-edition-2026",
    "title": "Update Article 3.13.3.13 Annex AC Athletes Committee Edition 2026.pdf",
    "category": "rulebook",
    "section": "ISSF Rule Book 2026",
    "webUrl": "https://www.issf-sports.org/rules",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=455&file=Update-Article-3.13.3.13-Annex-AC-Athletes-Committee-Edition-2026.pdf",
    "localPath": "/documents/issf/update-article-3-13-3-13-annex-ac-athletes-committee-edition-2026.pdf"
  },
  {
    "id": "update-shotgun-finals-edition-2026",
    "title": "Update Shotgun Finals Edition 2026.pdf",
    "category": "rulebook",
    "section": "ISSF Rule Book 2026",
    "webUrl": "https://www.issf-sports.org/rules",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=455&file=Update-Shotgun-Finals-Edition-2026.pdf",
    "localPath": "/documents/issf/update-shotgun-finals-edition-2026.pdf"
  },
  {
    "id": "issf-audit-committee",
    "title": "ISSF Audit Committee.pdf",
    "category": "committees",
    "section": "ISSF Rule Book 2026",
    "webUrl": "https://www.issf-sports.org/rules",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=455&iist=125&file=ISSF-Audit-Committee.pdf",
    "localPath": "/documents/issf/issf-audit-committee.pdf"
  },
  {
    "id": "nominations-committee-guidelines-final",
    "title": "Nominations Committee Guidelines final.pdf",
    "category": "committees",
    "section": "ISSF Rule Book 2026",
    "webUrl": "https://www.issf-sports.org/rules",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=455&iist=125&file=Nominations-Committee-Guidelines-final.pdf",
    "localPath": "/documents/issf/nominations-committee-guidelines-final.pdf"
  },
  {
    "id": "declaration-of-neutrality",
    "title": "Declaration of Neutrality.pdf",
    "category": "ain",
    "section": "ISSF Rule Book 2026",
    "webUrl": "https://www.issf-sports.org/rules",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=455&iist=166&file=Declaration-of-Neutrality.pdf",
    "localPath": "/documents/issf/declaration-of-neutrality.pdf"
  },
  {
    "id": "rules-for-the-participation-of-russian-and-belarusian-athletes-in-issf-competiti",
    "title": "Rules for the Participation of Russian and Belarusian Athletes in ISSF Competitions Version April 2026.pdf",
    "category": "ain",
    "section": "ISSF Rule Book 2026",
    "webUrl": "https://www.issf-sports.org/rules",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=455&iist=166&file=Rules-for-the-Participation-of-Russian-and-Belarusian-Athletes-in-ISSF-Competitions-Version-April-2026.pdf",
    "localPath": "/documents/issf/rules-for-the-participation-of-russian-and-belarusian-athletes-in-issf-competiti.pdf"
  },
  {
    "id": "issf-code-of-ethics-rule-book-2023-approved-version",
    "title": "ISSF Code of Ethics Rule Book 2023 Approved Version.pdf",
    "category": "integrity",
    "section": "Integrity & Ethics",
    "webUrl": "https://www.issf-sports.org/rules/code-of-ethics",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=465&iist=283&file=ISSF_Code-of-Ethics-Rule_Book_2023_Approved_Version.pdf",
    "localPath": "/documents/issf/issf-code-of-ethics-rule-book-2023-approved-version.pdf"
  },
  {
    "id": "issf-integrity-code-2025",
    "title": "ISSF Integrity Code 2025.pdf",
    "category": "integrity",
    "section": "Integrity & Ethics",
    "webUrl": "https://www.issf-sports.org/rules/code-of-ethics",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=465&iist=284&file=ISSF-Integrity-Code-2025.pdf",
    "localPath": "/documents/issf/issf-integrity-code-2025.pdf"
  },
  {
    "id": "issf-regulations-safeguarding-against-harassment-and-abuse",
    "title": "ISSF Regulations Safeguarding against Harassment and Abuse.pdf",
    "category": "safeguarding",
    "section": "Safeguarding",
    "webUrl": "https://www.issf-sports.org/rules/safeguarding-regulations",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=749&file=ISSF-Regulations-Safeguarding-against-Harassment-and-Abuse.pdf",
    "localPath": "/documents/issf/issf-regulations-safeguarding-against-harassment-and-abuse.pdf"
  },
  {
    "id": "issf-regulations-safeguarding-against-harassment-and-abuse-mark-up-against-previ",
    "title": "ISSF Regulations Safeguarding against Harassment and Abuse mark up against previous version.pdf",
    "category": "safeguarding",
    "section": "Safeguarding",
    "webUrl": "https://www.issf-sports.org/rules/safeguarding-regulations",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=749&file=ISSF-Regulations-Safeguarding-against-Harassment-and-Abuse_mark-up-against-previous-version.pdf",
    "localPath": "/documents/issf/issf-regulations-safeguarding-against-harassment-and-abuse-mark-up-against-previ.pdf"
  },
  {
    "id": "issf-disciplinary-regulations",
    "title": "ISSF Disciplinary Regulations.pdf",
    "category": "disciplinary",
    "section": "Disciplinary Regulations",
    "webUrl": "https://www.issf-sports.org/rules/disciplinary-regulations",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=518&file=ISSF-Disciplinary-Regulations.pdf",
    "localPath": "/documents/issf/issf-disciplinary-regulations.pdf"
  },
  {
    "id": "issf-criteria-for-eligibility-of-transgender-athletes",
    "title": "ISSF Criteria for Eligibility of Transgender Athletes.pdf",
    "category": "eligibility",
    "section": "Eligibility & Commercial Rights",
    "webUrl": "https://www.issf-sports.org/rules/eligibility",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=456&file=ISSF-Criteria-for-Eligibility-of-Transgender-Athletes.pdf",
    "localPath": "/documents/issf/issf-criteria-for-eligibility-of-transgender-athletes.pdf"
  },
  {
    "id": "25m-rfpm-malfunction-score-computation-form",
    "title": "25m RFPM Malfunction Score Computation Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=377&file=25m-RFPM-Malfunction-Score-Computation-Form.pdf",
    "localPath": "/documents/issf/25m-rfpm-malfunction-score-computation-form.pdf"
  },
  {
    "id": "25m-stpm-malfunction-score-computation-form",
    "title": "25m STPM Malfunction Score Computation Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=377&file=25m-STPM-Malfunction-Score-Computation-Form.pdf",
    "localPath": "/documents/issf/25m-stpm-malfunction-score-computation-form.pdf"
  },
  {
    "id": "appeal-form",
    "title": "Appeal Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=377&file=Appeal-Form.pdf",
    "localPath": "/documents/issf/appeal-form.pdf"
  },
  {
    "id": "dress-advertising-code-violation-warning-form",
    "title": "Dress Advertising Code Violation Warning Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=377&file=Dress-Advertising-Code-Violation-Warning-Form.pdf",
    "localPath": "/documents/issf/dress-advertising-code-violation-warning-form.pdf"
  },
  {
    "id": "protest-form",
    "title": "Protest Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=377&file=Protest-Form.pdf",
    "localPath": "/documents/issf/protest-form.pdf"
  },
  {
    "id": "range-incident-report-form",
    "title": "Range Incident Report Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=377&file=Range-Incident-Report-Form.pdf",
    "localPath": "/documents/issf/range-incident-report-form.pdf"
  },
  {
    "id": "rts-office-score-notification-form",
    "title": "RTS Office Score Notification Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=377&file=RTS-Office-Score-Notification-Form.pdf",
    "localPath": "/documents/issf/rts-office-score-notification-form.pdf"
  },
  {
    "id": "shotgun-incident-report-form",
    "title": "Shotgun Incident Report Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=377&file=Shotgun-Incident-Report-Form.pdf",
    "localPath": "/documents/issf/shotgun-incident-report-form.pdf"
  },
  {
    "id": "issf-post-championship-chief-referee-report-2026",
    "title": "ISSF Post Championship Chief Referee Report 2026.docx",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=23&file=ISSF-Post-Championship-Chief-Referee-Report-2026.docx",
    "localPath": "/documents/issf/issf-post-championship-chief-referee-report-2026-docx.pdf"
  },
  {
    "id": "issf-post-championship-jury-chairperson-report-2026",
    "title": "ISSF Post Championship Jury Chairperson Report 2026.docx",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=23&file=ISSF-Post-Championship-Jury-Chairperson-Report-2026.docx",
    "localPath": "/documents/issf/issf-post-championship-jury-chairperson-report-2026-docx.pdf"
  },
  {
    "id": "issf-post-championship-technical-delegate-report-2026",
    "title": "ISSF Post Championship Technical Delegate Report 2026.docx",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=23&file=ISSF-Post-Championship-Technical-Delegate-Report-2026.docx",
    "localPath": "/documents/issf/issf-post-championship-technical-delegate-report-2026-docx.pdf"
  },
  {
    "id": "issf-world-record-form",
    "title": "ISSF World Record Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=23&file=ISSF-World-Record-Form.pdf",
    "localPath": "/documents/issf/issf-world-record-form.pdf"
  },
  {
    "id": "issf-athlete-declaration-and-id-number-application-form-version-2025-update-2024",
    "title": "ISSF Athlete Declaration and ID Number Application Form Version 2025 Update 20241203.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=24&file=ISSF-Athlete-Declaration-and-ID-Number-Application-Form-Version-2025-Update-20241203.pdf",
    "localPath": "/documents/issf/issf-athlete-declaration-and-id-number-application-form-version-2025-update-2024.pdf"
  },
  {
    "id": "issf-athlete-declaration-and-issf-id-number-application-form-general-rules-versi",
    "title": "ISSF Athlete Declaration and ISSF ID Number Application Form General Rules Version 2025 Update 20241203.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=24&file=ISSF-Athlete-Declaration-and-ISSF-ID-Number-Application-Form-General-Rules-Version-2025-Update-20241203.pdf",
    "localPath": "/documents/issf/issf-athlete-declaration-and-issf-id-number-application-form-general-rules-versi.pdf"
  },
  {
    "id": "issf-athlete-declaration-version-2025-update-20241203",
    "title": "ISSF Athlete Declaration Version 2025 Update 20241203.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=24&file=ISSF-Athlete-Declaration-Version-2025-Update-20241203.pdf",
    "localPath": "/documents/issf/issf-athlete-declaration-version-2025-update-20241203.pdf"
  },
  {
    "id": "eyesight-examination-form",
    "title": "Eyesight Examination Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=22&file=Eyesight-Examination-Form.pdf",
    "localPath": "/documents/issf/eyesight-examination-form.pdf"
  },
  {
    "id": "issf-judges-course-application-form",
    "title": "ISSF Judges Course Application Form.docx",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=22&file=ISSF-Judges-Course-Application-Form.docx",
    "localPath": "/documents/issf/issf-judges-course-application-form-docx.pdf"
  },
  {
    "id": "judges-a-licence-application-form",
    "title": "Judges A Licence Application Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=22&file=Judges-A-Licence-Application-Form.pdf",
    "localPath": "/documents/issf/judges-a-licence-application-form.pdf"
  },
  {
    "id": "judges-b-licence-application-form",
    "title": "Judges B Licence Application Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=22&file=Judges-B-Licence-Application-Form.pdf",
    "localPath": "/documents/issf/judges-b-licence-application-form.pdf"
  },
  {
    "id": "judges-licence-renewal-application-form",
    "title": "Judges Licence Renewal Application Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=22&file=Judges-Licence-Renewal-Application-Form.pdf",
    "localPath": "/documents/issf/judges-licence-renewal-application-form.pdf"
  },
  {
    "id": "shotgun-referees-licence-application-form",
    "title": "Shotgun Referees Licence Application Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=22&file=Shotgun-Referees-Licence-Application-Form.pdf",
    "localPath": "/documents/issf/shotgun-referees-licence-application-form.pdf"
  },
  {
    "id": "shotgun-referees-licence-renewal-application-form",
    "title": "Shotgun Referees Licence Renewal Application Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=22&file=Shotgun-Referees-Licence-Renewal-Application-Form.pdf",
    "localPath": "/documents/issf/shotgun-referees-licence-renewal-application-form.pdf"
  },
  {
    "id": "issf-world-championship-application-form",
    "title": "ISSF World Championship Application Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=61&file=ISSF-World-Championship-Application-Form.pdf",
    "localPath": "/documents/issf/issf-world-championship-application-form.pdf"
  },
  {
    "id": "issf-world-cup-application-form",
    "title": "ISSF World Cup Application Form.pdf",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=61&file=ISSF-World-Cup-Application-Form.pdf",
    "localPath": "/documents/issf/issf-world-cup-application-form.pdf"
  },
  {
    "id": "issf-expenses-claim-form-2026",
    "title": "ISSF Expenses Claim Form 2026.xlsx",
    "category": "forms",
    "section": "Forms",
    "webUrl": "https://www.issf-sports.org/rules/forms",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=29&iist=172&file=ISSF-Expenses-Claim-Form-2026.xlsx",
    "localPath": "/documents/issf/issf-expenses-claim-form-2026-xlsx.pdf"
  },
  {
    "id": "issf-approved-clay-targets-and-clay-target-machines-november-2025",
    "title": "ISSF approved Clay Targets and Clay Target Machines November 2025.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=29&file=ISSF-approved-Clay-Targets-and-Clay-Target-Machines-November-2025.pdf",
    "localPath": "/documents/issf/issf-approved-clay-targets-and-clay-target-machines-november-2025.pdf"
  },
  {
    "id": "issf-approved-est-may-2026",
    "title": "ISSF approved EST May 2026.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=29&file=ISSF-approved-EST-May-2026.pdf",
    "localPath": "/documents/issf/issf-approved-est-may-2026.pdf"
  },
  {
    "id": "issf-criteria-for-eligibility-of-transgender-athletes",
    "title": "ISSF Criteria for Eligibility of Transgender Athletes.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=29&file=ISSF-Criteria-for-Eligibility-of-Transgender-Athletes.pdf",
    "localPath": "/documents/issf/issf-criteria-for-eligibility-of-transgender-athletes.pdf"
  },
  {
    "id": "issf-indemnity-attendances-fees-and-travel-expenses-guidelines-20250108",
    "title": "ISSF Indemnity Attendances Fees and Travel Expenses Guidelines 20250108.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=29&file=ISSF-Indemnity-Attendances-Fees-and-Travel-Expenses-Guidelines-20250108.pdf",
    "localPath": "/documents/issf/issf-indemnity-attendances-fees-and-travel-expenses-guidelines-20250108.pdf"
  },
  {
    "id": "issf-integrity-code-2025",
    "title": "ISSF Integrity Code 2025.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=29&file=ISSF-Integrity-Code-2025.pdf",
    "localPath": "/documents/issf/issf-integrity-code-2025.pdf"
  },
  {
    "id": "issf-regulations-safeguarding-against-harassment-and-abuse",
    "title": "ISSF Regulations Safeguarding against Harassment and Abuse.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=29&file=ISSF-Regulations-Safeguarding-against-Harassment-and-Abuse.pdf",
    "localPath": "/documents/issf/issf-regulations-safeguarding-against-harassment-and-abuse.pdf"
  },
  {
    "id": "issf-rules-for-paper-target-scoring",
    "title": "ISSF Rules for Paper Target Scoring.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=29&file=ISSF-Rules-for-Paper-Target-Scoring.pdf",
    "localPath": "/documents/issf/issf-rules-for-paper-target-scoring.pdf"
  },
  {
    "id": "issf-data-protection-regulation",
    "title": "ISSF Data Protection Regulation.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=29&file=ISSF_Data_Protection_Regulation.pdf",
    "localPath": "/documents/issf/issf-data-protection-regulation.pdf"
  },
  {
    "id": "issf-notice-personal-data",
    "title": "ISSF Notice Personal Data.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=29&file=ISSF_Notice_Personal_Data.pdf",
    "localPath": "/documents/issf/issf-notice-personal-data.pdf"
  },
  {
    "id": "issf-rule-interpretation-for-2017-issf-rules-6-3-6-definition-eco-friendly",
    "title": "ISSF Rule Interpretation for 2017 ISSF Rules 6.3.6 Definition eco friendly.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=29&file=ISSF_Rule_Interpretation_for_2017_ISSF_Rules_6.3.6_Definition_eco-friendly.pdf",
    "localPath": "/documents/issf/issf-rule-interpretation-for-2017-issf-rules-6-3-6-definition-eco-friendly.pdf"
  },
  {
    "id": "issf-safeguarding-quick-fact-sheet-2018",
    "title": "ISSF Safeguarding Quick Fact Sheet 2018.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=29&file=ISSF_Safeguarding_Quick_Fact_Sheet_2018.pdf",
    "localPath": "/documents/issf/issf-safeguarding-quick-fact-sheet-2018.pdf"
  },
  {
    "id": "final-commands-and-announcements-edition-2026-version-february-2026",
    "title": "Final Commands and Announcements   Edition 2026   Version February 2026.zip",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=62&file=Final_Commands_and_Announcements_-_Edition_2026_-_Version_February_2026.zip",
    "localPath": "/documents/issf/final-commands-and-announcements-edition-2026-version-february-2026-zip.pdf"
  },
  {
    "id": "issf-medal-ceremony-script-2026",
    "title": "ISSF Medal Ceremony Script 2026.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=62&file=ISSF-Medal-Ceremony-Script-2026.pdf",
    "localPath": "/documents/issf/issf-medal-ceremony-script-2026.pdf"
  },
  {
    "id": "manual-for-issf-rts-officers-edition-2026",
    "title": "Manual for ISSF RTS Officers Edition 2026.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=25&file=Manual-for-ISSF-RTS-Officers-Edition-2026.pdf",
    "localPath": "/documents/issf/manual-for-issf-rts-officers-edition-2026.pdf"
  },
  {
    "id": "rifle-equipment-control-guide-edition-2026",
    "title": "Rifle Equipment Control Guide Edition 2026.pdf",
    "category": "rifle",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=25&file=Rifle-Equipment-Control-Guide-Edition-2026.pdf",
    "localPath": "/documents/issf/rifle-equipment-control-guide-edition-2026.pdf"
  },
  {
    "id": "rifle-annex-a-issf-instructions-for-conducting-shoe-sole-flexibility-tests-editi",
    "title": "Rifle Annex A ISSF Instructions for Conducting Shoe Sole Flexibility Tests   Edition 2018.pdf",
    "category": "rifle",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=25&file=Rifle_Annex_A_ISSF_Instructions_for_Conducting_Shoe_Sole_Flexibility_Tests_-_Edition_2018.pdf",
    "localPath": "/documents/issf/rifle-annex-a-issf-instructions-for-conducting-shoe-sole-flexibility-tests-editi.pdf"
  },
  {
    "id": "rifle-annex-b-issf-equipment-control-measurement-form-edition-2018",
    "title": "Rifle Annex B ISSF Equipment Control Measurement Form   Edition 2018.pdf",
    "category": "rifle",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=25&file=Rifle_Annex_B_ISSF_Equipment_Control_Measurement_Form_-_Edition_2018.pdf",
    "localPath": "/documents/issf/rifle-annex-b-issf-equipment-control-measurement-form-edition-2018.pdf"
  },
  {
    "id": "rifle-annex-c-issf-equipment-control-code-violation-warning-form-eq-edition-2018",
    "title": "Rifle Annex C ISSF Equipment Control Code Violation Warning Form   EQ   Edition 2018.pdf",
    "category": "rifle",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=25&file=Rifle_Annex_C_ISSF_Equipment_Control_Code_Violation_Warning_Form_-_EQ_-_Edition_2018.pdf",
    "localPath": "/documents/issf/rifle-annex-c-issf-equipment-control-code-violation-warning-form-eq-edition-2018.pdf"
  },
  {
    "id": "training-manual-rifle-for-issf-range-officials-and-judges-edition-2018",
    "title": "Training Manual Rifle for ISSF Range Officials and Judges   Edition 2018.pdf",
    "category": "rifle",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=25&file=Training_Manual_Rifle_for_ISSF_Range_Officials_and_Judges_-_Edition_2018.pdf",
    "localPath": "/documents/issf/training-manual-rifle-for-issf-range-officials-and-judges-edition-2018.pdf"
  },
  {
    "id": "explanation-of-new-pistol-grip-rules-2026",
    "title": "Explanation of New Pistol Grip Rules 2026.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=26&file=Explanation-of-New-Pistol-Grip-Rules-2026.pdf",
    "localPath": "/documents/issf/explanation-of-new-pistol-grip-rules-2026.pdf"
  },
  {
    "id": "manual-for-issf-rts-officers-edition-2026",
    "title": "Manual for ISSF RTS Officers Edition 2026.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=26&file=Manual-for-ISSF-RTS-Officers-Edition-2026.pdf",
    "localPath": "/documents/issf/manual-for-issf-rts-officers-edition-2026.pdf"
  },
  {
    "id": "pistol-annex-b-procedures-for-rfp-ammunition-velocity-tests-edition-2026",
    "title": "Pistol Annex B Procedures for RFP Ammunition Velocity Tests Edition 2026.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=26&file=Pistol-Annex-B-Procedures-for-RFP-Ammunition-Velocity-Tests-Edition-2026.pdf",
    "localPath": "/documents/issf/pistol-annex-b-procedures-for-rfp-ammunition-velocity-tests-edition-2026.pdf"
  },
  {
    "id": "pistol-annex-a-issf-instructions-for-conducting-shoe-sole-flexibility-tests-edit",
    "title": "Pistol Annex A ISSF Instructions for Conducting Shoe Sole Flexibility Tests   Edition 2018.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=26&file=Pistol_Annex_A_ISSF_Instructions_for_Conducting_Shoe_Sole_Flexibility_Tests_-_Edition_2018.pdf",
    "localPath": "/documents/issf/pistol-annex-a-issf-instructions-for-conducting-shoe-sole-flexibility-tests-edit.pdf"
  },
  {
    "id": "pistol-equipment-control-guide-edition-2018",
    "title": "Pistol Equipment Control Guide   Edition 2018.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=26&file=Pistol_Equipment_Control_Guide_-_Edition_2018.pdf",
    "localPath": "/documents/issf/pistol-equipment-control-guide-edition-2018.pdf"
  },
  {
    "id": "training-manual-pistol-for-issf-range-officials-and-judges-edition-2018",
    "title": "Training Manual Pistol for ISSF Range Officials and Judges   Edition 2018.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=26&file=Training_Manual_Pistol_for_ISSF_Range_Officials_and_Judges_-_Edition_2018.pdf",
    "localPath": "/documents/issf/training-manual-pistol-for-issf-range-officials-and-judges-edition-2018.pdf"
  },
  {
    "id": "shotgun-annex-a-shotgun-cartridge-control-form-edition-2026",
    "title": "Shotgun Annex A Shotgun Cartridge Control Form Edition 2026.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=28&file=Shotgun-Annex-A-Shotgun-Cartridge-Control-Form-Edition-2026.pdf",
    "localPath": "/documents/issf/shotgun-annex-a-shotgun-cartridge-control-form-edition-2026.pdf"
  },
  {
    "id": "shotgun-equipment-control-guide-edition-2026",
    "title": "Shotgun Equipment Control Guide Edition 2026.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=28&file=Shotgun-Equipment-Control-Guide-Edition-2026.pdf",
    "localPath": "/documents/issf/shotgun-equipment-control-guide-edition-2026.pdf"
  },
  {
    "id": "shotgun-jury-guidelines-edition-2026",
    "title": "Shotgun Jury Guidelines Edition 2026.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=28&file=Shotgun-Jury-Guidelines-Edition-2026.pdf",
    "localPath": "/documents/issf/shotgun-jury-guidelines-edition-2026.pdf"
  },
  {
    "id": "training-manual-shotgun-for-issf-range-officials-and-judges-edition-2026",
    "title": "Training Manual Shotgun for ISSF Range Officials and Judges Edition 2026.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=28&file=Training-Manual-Shotgun-for-ISSF-Range-Officials-and-Judges-Edition-2026.pdf",
    "localPath": "/documents/issf/training-manual-shotgun-for-issf-range-officials-and-judges-edition-2026.pdf"
  },
  {
    "id": "manual-for-issf-rts-officers-edition-2026",
    "title": "Manual for ISSF RTS Officers Edition 2026.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=27&file=Manual-for-ISSF-RTS-Officers-Edition-2026.pdf",
    "localPath": "/documents/issf/manual-for-issf-rts-officers-edition-2026.pdf"
  },
  {
    "id": "training-manual-running-target-for-issf-range-officials-and-judges-edition-2018",
    "title": "Training Manual Running Target for ISSF Range Officials and Judges   Edition 2018.pdf",
    "category": "guides",
    "section": "Amendments & Interpretation",
    "webUrl": "https://www.issf-sports.org/rules/amendments-and-interpretation",
    "pdfUrl": "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=31&iist=27&file=Training_Manual_Running_Target_for_ISSF_Range_Officials_and_Judges_-_Edition_2018.pdf",
    "localPath": "/documents/issf/training-manual-running-target-for-issf-range-officials-and-judges-edition-2018.pdf"
  }
];
