/** Generated by scripts/build-rule-index.mjs — do not edit by hand. */
export const RULES_INDEX_META = {
  lastCheckedAgainstIssf: '2026-08-19',
  generatedAt: '2026-08-19T22:28:50.812Z',
  officialPortal: 'https://www.issf-sports.org/rules',
  currentRulebook: {
    title: "ISSF Rule Book 2026",
    edition: "2026 Edition 2025",
    print: "Second Print 07/2026",
    effectiveDate: "1 July 2026",
    localPath: "/documents/issf/issf-rule-book-2026-edition-2025-second-print-07-2026-effective-1-july-2026.pdf",
    officialPdf: "https://backoffice.issf-sports.org/getfile.aspx?mod=docf&pane=1&inst=455&file=ISSF-Rule-Book-2026-Edition-2025-Second-Print-07-2026-Effective-1-July-2026.pdf",
  },
  documentsIndexed: 2,
  pagesIndexed: 194,
  sectionsIndexed: 1212,
  warnings: ["Rulebook empty-ish pages in range: 6","rifle-equipment-control-guide-edition-2026.pdf: 1 sparse pages"],
} as const;
